services:
  candle_scraper:
    container_name: candle_scraper
    build: .
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - EMAIL=${EMAIL}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - RECIPIENT_EMAIL=${RECIPIENT_EMAIL}
      - BASE_URL=${BASE_URL}
      - THREE_WICK_URL=${THREE_WICK_URL}
      - SINGLE_WICK_URL=${SINGLE_WICK_URL}

  db:
    container_name: postgres
    image: postgres
    ports:
      - '5432:${DB_PORT}'
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

volumes:
  db-data: 

